ALTER TABLE venues ADD COLUMN IF NOT EXISTS city VARCHAR(120);
UPDATE venues SET city = COALESCE(city, 'Bogotá');
ALTER TABLE venues ALTER COLUMN city SET NOT NULL;

ALTER TABLE events ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE;
UPDATE events SET active = COALESCE(active, TRUE);
ALTER TABLE events ALTER COLUMN active SET NOT NULL;

ALTER TABLE events ADD COLUMN IF NOT EXISTS venue_id INTEGER;

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS events_categories (
    event_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    CONSTRAINT pk_events_categories PRIMARY KEY (event_id, category_id)
);

INSERT INTO venues (name, address, city, capacity)
SELECT 'Legacy Venue', 'Legacy migrated venue', 'Bogotá', 0
WHERE NOT EXISTS (SELECT 1 FROM venues);

UPDATE events
SET venue_id = COALESCE(venue_id, (SELECT MIN(id) FROM venues));

ALTER TABLE events ALTER COLUMN venue_id SET NOT NULL;

ALTER TABLE events
    ADD CONSTRAINT fk_events_venue
    FOREIGN KEY (venue_id) REFERENCES venues (id);

ALTER TABLE events_categories
    ADD CONSTRAINT fk_events_categories_event
    FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE events_categories
    ADD CONSTRAINT fk_events_categories_category
    FOREIGN KEY (category_id) REFERENCES categories (id);
